"""add_owner_fields

Revision ID: aa34f3047d52
Revises: 2ba0dc6c27fb
Create Date: 2026-03-20 00:34:16.449166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa34f3047d52'
down_revision: Union[str, None] = '2ba0dc6c27fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salons', sa.Column('owner_whatsapp_number', sa.String(length=50), nullable=True))
    op.add_column('salons', sa.Column('owner_access_token', sa.String(length=100), nullable=True))
    op.add_column('salons', sa.Column('notify_on_booking', sa.Boolean(), nullable=False, server_default='true'))
    op.create_index(op.f('ix_salons_owner_access_token'), 'salons', ['owner_access_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salons_owner_access_token'), table_name='salons')
    op.drop_column('salons', 'notify_on_booking')
    op.drop_column('salons', 'owner_access_token')
    op.drop_column('salons', 'owner_whatsapp_number')
    # ### end Alembic commands ###
